version: '3.8'

services:
  landing-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: landing-api
    restart: always
    depends_on:
      - postgres
    networks:
      - proxy_net
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=LandingPage
      - DATABASE_URL=mongodb://root:root@db:27017/LandingPage?authSource=admin
      - PASSWORD_SEED=SecretoContraseña
      - ADMIN_EMAIL="AndreaStudent@gmail.com"
      - ADMIN_PASSWORD="Abc123"
      - ADMIN_NAME="Kevin Mondragon"
      - ADMIN_MATRICULA="021000123"
      - JWT_SECRET=Secreto
      - PORT=3000

  postgres:
    image: mongo
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy_net

volumes:
  postgres_data:

networks:
  proxy_net:
    external: true
